#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

##############################################################################


# [ BASIC ] ##################################################################
# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme.toml config
leftwm-command "LoadTheme $HOME/.config/leftwm/themes/current/theme.toml"
##############################################################################




# [ RUN STUFF ] ##############################################################
# keybindings daemon (if it exist)
if [ -x "$(command -v sxhkd)" ]; then
    sxhkd -c $HOME/.config/leftwm/sxhkd/sxhkdrc &
fi

# apps
numlockx on &

# notifications
if [ -x "$(command -v dunst)" ]; then
  pkill dunst
  dunst -config $HOME/.config/leftwm/themes/current/conf/dunst.config &
fi
#/usr/lib/xfce4/notifyd/xfce4-notifyd &


# picom (if it exists)
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/leftwm/themes/current/conf/picom.config &> /dev/null &
fi
##############################################################################




# [ WALLPAPERS ] #############################################################
# - Comment/uncomment the option you prefer

# 1) START - set random wallpapers -----------------------------------------+
if [ -x "$(command -v feh)" ]; then
  feh --randomize --bg-fill "$SCRIPTPATH"/wallpapers/* --no-fehbg
fi
# END ----------------------------------------------------------------------+


# 2) START - set ONE wallpaper for all displays ----------------------------+
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-fill "$SCRIPTPATH"/wallpapers/atlas-ark-gruvbox-simple-lines.png
#fi
# END ----------------------------------------------------------------------+


# 3) START - set MULTIPLE wallpapers for all displays ----------------------+
# NOTE: the last image path DO NOT end with "\"
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-fill \
#  "$SCRIPTPATH"/wallpapers/blue_unicat.png \
#  "$SCRIPTPATH"/wallpapers/pink_unicat.png
#fi
# END ----------------------------------------------------------------------+
##############################################################################



# [ START STATUSBAR ] #########################################################
~/.config/leftwm/themes/current/polybar/launch.sh &
######################################################################
