modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "LeftMain", "CenterMain", "CenterMainBalanced", "CenterMainFluid", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
layout_mode = "Workspace"
insert_behavior = "Bottom"
scratchpad = []
window_rules = []
disable_current_tag_swap = false
disable_tile_drag = true
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "Execute"
value = "rofi -modi 'drun' -show drun -show-icons"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "Execute"
value = "rofi -modi 'combi' -show combi -show-icons"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "Execute"
value = "rofi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}'"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "Execute"
value = "~/.scripts/github.com/noahdotpy/.dotfiles/rofi-powermenu.sh"
modifier = ["modkey", "Shift"]
key = "Escape"

[[keybind]]
command = "Execute"
value = "rofi -modi emoji -show emoji"
modifier = ["modkey"]
key = "period"

[[keybind]]
command = "Execute"
value = "kitty"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey", "Shift"]
key = "c"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "~/.config/leftwm/themes/current/lock-screen.sh"
modifier = ["modkey", "Shift", "Control"]
key = "l"

# Go to previous tag (essentialy an alt+tab from windows but for tags)
[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey"]
key = "w"


# Window properties changing

# ! DOESNT WORK FOR SOME REASON
[[keybind]]
command = "ToggleFloating"
modifier = ["modkey", "Control"]
key = "f"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey", "Shift"]
key = "f"

# shown on all workspaces
# best with floating windows (picture-in-picture especially)
[[keybind]]
command = "ToggleSticky"
modifier = ["modkey", "Control"]
key = "v"


# Window moving

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey", "Shift"]
key = "t"


# Window navigation

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "j"


# Layout changing

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "j"


# Layout modifying

[[keybind]]
command = "IncreaseMainWidth"
value = "3"
modifier = ["modkey", "Shift"]
key = "l"

[[keybind]]
command = "IncreaseMainWidth"
value = "3"
modifier = ["modkey", "Shift"]
key = "Right"

[[keybind]]
command = "DecreaseMainWidth"
value = "3"
modifier = ["modkey", "Shift"]
key = "h"

[[keybind]]
command = "DecreaseMainWidth"
value = "3"
modifier = ["modkey", "Shift"]
key = "Left"


# Switch to screen

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "h"


# Just basic tag keybinds

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "GotoTag"
value = "10"
modifier = ["modkey"]
key = "0"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "10"
modifier = ["modkey", "Shift"]
key = "0"
