#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
greenclip daemon &
flatpak run com.getmailspring.Mailspring --background &

# Turn off system BEEP
xset b off &
xset b 0 0 0 &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Setting layouts with bsp-layout
bsp-layout set tall 1 --master-size 0.5
bsp-layout set tall 2 --master-size 0.5
bsp-layout set tall 3 --master-size 0.5
bsp-layout set tall 4 --master-size 0.5
bsp-layout set tall 5 --master-size 0.5
bsp-layout set tall 6 --master-size 0.5
bsp-layout set tall 7 --master-size 0.5
bsp-layout set tall 8 --master-size 0.5
bsp-layout set tall 9 --master-size 0.5
bsp-layout set tall 10 --master-size 0.5

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a ksnip state=floating
