#! /usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
greenclip daemon &
flatpak run com.getmailspring.Mailspring --background &

WORKSPACES_AS_STRING=""
for i in {1..10}
do
  # Define var to use for bspc monitor -d
  WORKSPACES_AS_STRING="$WORKSPACES_AS_STRING $i"

  # Setting layouts with bsp-layout
  bsp-layout set tall $i --master-size 0.5
done

# Workspaces
bspc monitor -d $WORKSPACES_AS_STRING


bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Turn off system BEEP
xset b off &
xset b 0 0 0 &

# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a ksnip state=floating
