#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
greenclip daemon &
flatpak run com.getmailspring.Mailspring --background &

# Turn off system BEEP
xset b off &
xset b 0 0 0 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a ksnip state=floating
